
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_DEFAULT_VAL 255
#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_HUE 169  // blue
#define RGBLIGHT_DEFAULT_SPD 100

#define TAPPING_TERM 180
